<!DOCTYPE HTML>

<html>
<?php
$SITE_SUBTITLE='Frequently asked questions';
include('head.php');
?>

<body>

<?php
$SITE_TAB='faq';
include('header.php');
?>

<div id="content">
  <div id="content-container">

  Here is a list of frequently asked questions. Feel free to send any suggestions to
  support (at) magictunnel.net. While we cannot answer to all the e-mails we get, we will do our best to apply your feedback and make MagicTunnel better. If you
submit a bug report, attach the output of the MagicTunnel log, as well as a detailed description of how to reproduce the bug.

  <h3>How fast is DNS tunneling?</h3>
  You can expect a throughput anywhere from 1 to 10 KB/s on typical DNS servers (both over 3G and Wifi). The latency can be up to several seconds. In general, do
not
expect to be able to
browse heavy web sites or place VoIP calls. Of course, we also encountered DNS servers that are fast enough to stream (low definition) videos...

  <h3>What can I use DNS tunneling for?</h3>
  Mostly to send and receive e-mails and for other lightweight activities. See the previous point.

  <h3>Does MagicTunnel use encryption?</h3>
  No, it does not. It is up to you to encrypt your traffic or use services that provide encryption (SSL-enabled Web sites, IMAP, POP, or SMTP). Keep in mind that most DNS servers keep a log of the DNS queries, making it possible to know the content of the Web pages your visit for a long time.

  <h3>Does MagicTunnel always work?</h3>
  Yes, provided that the ISP's DNS server allows queries to external DNS servers and does not filter unusual DNS queries. If the ISP does not allow such queries or filters them, MagicTunnel cannot help you in any way.

   <h3>Do I need to configure the firewall on my phone?</h3>
   It depends on your firewall. MagicTunnel has been tested to work ok without any specific configuration when <a href="https://code.google.com/p/droidwall/">Droidwall</a> is active. If in doubt, disable your firewall.

<h3>MagicTunnel reports "Connected" but I can't browse the Internet</h3>
<p>
  This may  happen when the ISP resets your IP address or the Wifi drops the connection. In this case,  disconnect the tunnel (long press on the tunnel name), disable your network connection, enable it again, then establish the tunnel.
</p>

<p>
       If it does not help, check that your domain name is setup properly and your DNS server is properly configured. You can check this by running the <tt>iodine</tt> client on a PC connected to the Internet. If it works, check the connection log in the MagicTunnel client.
</p>

<h3>How to file bug reports or feature requests?</h3>
       There are dozens of types of Android phones out there, many of which are customized by their manufacturers. We cannot test MagicTunnel on each of them, but
will be happy to resolve bugs as they come. Feel
free to send bug reports to support (at)
magictunnel.net. Each report must contain the connection log generated by MagicTunnel, the brand/model of the phone, firmware, as well as an accurate description of
the bug. Of course, we also welcome suggestions for new features!

  </div>
</div>

</body>
</html>
